### ISSUE TITLE
hardcoded credentials - parameterize instead

### ISSUE THREAD

**Issue by paralax** [haroonawanofficial/ReconCobra#11]
your modules have API creds hard coded in some places. you should:

* rotate creds, those are now compromised
* parameterize them with a .conf file or something

**Comment by haroonawanofficial** [comment]
Good idea, but do show me screenshots and I can make conf file for it in update

**Comment by haroonawanofficial** [comment]
Known issue is with censys.py.

Enter your own APIS in censys.io , get it from censys.io

**Comment by paralax** [comment]
the problem isn't that they're not my credentials, the problem is that with them on github everyone can see your credentials and use up your API credits. 

https://geekflare.com/github-credentials-scanner/

https://www.zdnet.com/article/over-100000-github-repos-have-leaked-api-or-cryptographic-keys/

etc etc etc

**Comment by haroonawanofficial** [comment]
Not a issue, these were created as Bogus and Fake API(s) specifically for this purpose.  I mentioned API in README sections, where are they.
