### ISSUE TITLE
ReconCobra Not Starting

### ISSUE THREAD

**Issue by albertservices** [haroonawanofficial/ReconCobra#13]
geckodriver
[*] Setup script completed successfully, enjoy EyeWitness! :)
[*] Be sure to check out FortyNorth Security!
[*] https://www.fortynorthsecurity.com

ReconCobra Successfully Installed, Starting
Can't locate HTML/TableExtract.pm in @INC (you may need to install the HTML::TableExtract module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/ReconCobra/ReconCobra.pl line 38.
BEGIN failed--compilation aborted at /usr/share/ReconCobra/ReconCobra.pl line 38.

**Comment by haroonawanofficial** [comment]
Enter this in terminal. I will update installer
1. Cpan -fi HTML::TableExtract
Or
2. perl -MCPAN -e shell
 HTML::TableExtract

It will start. Confirm?

**Comment by albertservices** [comment]
I'll check and update you asap.

**Comment by haroonawanofficial** [comment]
Clone again and install again, it will fix error and start.

**Comment by albertservices** [comment]
Cloned again, no good. Same error.

**Comment by albertservices** [comment]
Tried the above commands, no good.
Running on Kali Linux

**Comment by albertservices** [comment]
Nevermind, how can I be so stupid....Was running black arch installer instead of kali's. Sorry.
