### ISSUE TITLE
No module is working...

### ISSUE THREAD

**Issue by soufianetahiri** [haroonawanofficial/ReconCobra#9]
The install was tested on an updated version of Parrot and Kali.
The install itself went with no problem but once executed: NO MODULE IS WORKING.

![image](https://user-images.githubusercontent.com/17729335/71191502-d4d65600-2286-11ea-85d1-d02ea83d6282.png)
![image](https://user-images.githubusercontent.com/17729335/71191637-1ff06900-2287-11ea-914b-b8b0ff57a94c.png)

I think you should probably add some uninstall script :)
Thanks the tool is a great idea by the way !

**Comment by jepunband** [comment]
yes an uninstall script will be a good idea..same here some modules do not work.

**Comment by haroonawanofficial** [comment]
Paths,
/usr/share/ReconCobra
/usr/share/local/ReconCobra
/ReconCobra

In all these directories do this, chmod u+x * then run software, all modules will work

**Comment by jepunband** [comment]
same problem, did not fix the issue with the given solution.

**Comment by haroonawanofficial** [comment]
Try this, 
Enter perl then ctrl c
Enter python2 then ctrl d
Enter python3 then ctrl d

This will create environment. Then modules should work then.

**Comment by jepunband** [comment]
hi it still did not solve number 1. module. So far most of the modules are working after doing some tests.
i have encountered errors on these modules:

1. website information
error:
[!] Something Went Wrong
[Note] Enter Website Without HTTP/HTTPs


65.Find Subdomains using API Searcher > Censys API Search
error:
sh: 1: ./cleaner.sh: Permission denied
sh: 1: ./checker.sh: Permission denied

Aslo if possible to go back to main menu when ctrl+c during scans. Cos now it just exits. so have to re-launch the program everytime...

**Comment by haroonawanofficial** [comment]
Mostly errors are related to permission, ur perl don't have permission to do anything. 

Paths I have been given, use this command on paths, that would change all files, directories writable and readable by perl.

chmod -R 755 /usr/share/ReconCobra

 chmod -R 755  /usr/share/local/ReconCobra

chmod -R 755 /ReconCobra

This will fix any errors of permission related.

Confirm here, if this fix it?

After that provide me, what modules are not working. I can fix them. It is private project so I need more details to fix errors for other systems.

**Comment by senseworld** [comment]
> chmod -R 777 /usr/share/local/ReconCobra
> 
> chmod -R 777 /ReconCobra
> 
> This will fix any errors of permission related.

>These paths don't exist in the Kali installation. Modules 1 and 2 are not working.
This was a major installation and doesn't seem to provide any useful automation. It just gives a menu for functions that are already available in Kali or online. How do we link the menu options in order to automate? It provides no reporting, it resizes my terminal and it clears the screen after each tool is run. Why are there no options to run a number of tests and save the output?

**Comment by haroonawanofficial** [comment]
Run installer again and ReconCobra will automatically fix errors mentioned here. 
Modules 1 and modules 2, are working now.

Issue is heavy duty queries are being made from this tool,  websites change their verifications.

senseworld, I really don't see your point. Everything is online, earlier made and free. ReconCobra combine that, and gives us what we want, we want to sweep in automation, it do that and save results in file, we want subdomains (more than sublist3r) it do that remove duplication, give us clean 
result with cnames for possible hijack, in less than 1 minute.

It is not made for newbies, those who know what is footprinting, passive or active, it do that and save our time. Nobody remember heavy commands, it saves time.

**Comment by haroonawanofficial** [comment]
Provide me ideas, suggestions, I can implement that as this tool was made for private use only for my Mac OS, Linux and Parrot OS.

**Comment by soufianetahiri** [comment]
Reinstalling, will check and get back to you.


PS: its toxic talking about newbies especially when you include an Instagram account to follow :)

**Comment by soufianetahiri** [comment]
Still getting same errors, and it would be as painful to fix everything as running each script individually at need :)

the tool stills a good idea good luck :)

**Comment by mukhilanpari** [comment]
Same issue.

did chmod u+x for /usr/share/ReconCobra & /ReconCobra

but this folder i cant able to find /usr/share/local/ReconCobra . 

and checked perl, python2 and python3 env. 

None of the module worked for me. Tools looks great.

**Comment by haroonawanofficial** [comment]
This issue is related to your permissions. Either your own different OS or your not root.

Tell me few things.

1. Are you root?
2. Are you using Kali?
3. Are you using Termux?
4. Show, uname -a , output
5. Show, whoami, output
6. Show, id , output
7. Show screenshot of your terminal


Provide me these

**Comment by abroyhill** [comment]
Same issue, but output showing 

[~]Make sss.sh available in same folder
[~] Command failed

I can run sss.sh perfectly fine outside of ReconCobra, along with any other .sh

**Comment by haroonawanofficial** [comment]
U have permission related errors. Try to do this:
su ReconCobra
sudo ReconCobra

**Comment by soufianetahiri** [comment]
┌─[root@xx]─[~]
└──╼ #whoami
root
┌─[✗]─[root@xx]─[~]
└──╼ #id
uid=0(root) gid=0(root) groups=0(root)
└──╼ #uname -a
Linux xx 5.3.0-kali3-amd64 #1 SMP Debian 5.3.15-1kali1 (2019-12-09) x86_64 GNU/Linux

No its not only a permission related error, it seems so but NO it is not.

**Comment by haroonawanofficial** [comment]
Yes. Shoe me output of 

which ReconCobra.
It will locate package if successfully installed.

**Comment by haroonawanofficial** [comment]
Clone again and install again, it will fix errors mentioned here

**Comment by shanow7** [comment]
I've promblem with 17th modul's
![image](https://user-images.githubusercontent.com/37192410/72016476-2198c580-3264-11ea-90a9-97b93b3679da.png)

**Comment by haroonawanofficial** [comment]
I am fixing it and I will let you know

**Comment by haroonawanofficial** [comment]
Clone this respiratory and run installer, this issue will be gone.

**Comment by soufianetahiri** [comment]
Will give it a try later today and get back to you

**Comment by soufianetahiri** [comment]
previously not working modules are working know.
I did a forced clone to replace previously cloned repo chmoded .sh files and run the kalisetup.
the issue is "closed" for me.
Thanks for the great work :)

**Comment by johndoehack** [comment]
no module is working. plus there is an error for blackarch (instead of using pacman apt is used)
kali linux installation no modules running. error return after running software script

**Comment by haroonawanofficial** [comment]
Probably installers are mixed. I fix blackarch installer in few hours

**Comment by haroonawanofficial** [comment]
Try Black Arch Installer, it was mixed as apt-get install, I fixed it as pacman -S package, it should work, do confirm back.

**Comment by johndoehack** [comment]
error in code for blackarch. it use apt instead of pacman. aptitude is not available for arch or blackarch.

**Comment by haroonawanofficial** [comment]
All fixed. Check installers n uninstallers. They will work
